version: "3.1"
services:
  postgres:
    image: postgres
    container_name: "postgres-container"
    ports:
      - 5432:5432

  task-rest-api:
    build:
      context: .
    image: "task-api"
    environment:
      DB_URI: mongodb://mongo:27017/db
    depends_on:
      - cache
      - mongo
    ports:
      - 5000:5000
